### ISSUE TITLE
Wait before deleting a node

### ISSUE THREAD

**Issue by p1gmale0n** [rapido-labs/silent-assassin#8]
First, I want to thank you for your work. Great and much needed project!

**Overview:**
In our case, we have only one running preemptible node. The new node does not have time to start before the old one is deleted.
It would be nice to be able to adjust the wait-time between drain and kill node.

**Comment by sandeeprapido** [comment]
You Should not have only one Preemptible node. You should have at least 2 nodes running. Adjusting the wait time between the drain and kill does not help as the pod would have got deleted when SA drains the node.
